### ISSUE TITLE
Support Python 3.11

### ISSUE THREAD

**Issue by csadorf** [aiidalab/aiidalab-docker-stack#265]
Adopt Python 3.11 as the primary Python version in AiiDAlab.

## TODO list

- [x] Bump watchdog dependency in `aiidalab` package https://github.com/aiidalab/aiidalab/pull/328
- [x] Verify that `optimade-client` works with Python 3.10 https://github.com/CasperWA/voila-optimade-client/pull/474
- [x] Verify AWB and QeApp can be installed with Python 3.11, this can be done by automatic integration test on this repo
- [ ] Manually test that everything works
- [ ] Bump Python version in Docker stack #455

**Comment by danielhollas** [comment]
I think it might be better to jump straight to 3.11 for the following reasons:

1. 3.11 will give us an immediate tangible benefit as it should be measurably faster than 3.10/3.9. For my app I tested it improves to loading time of my app by 600 ms.

2. Currently, when we bump the Python version, we break all the existing deployments, since the python dependencies of the Apps need to be reinstalled, see #317. We currently don't provide any good mechanism to reinstall all the install apps, or at least warn the user, so to minimize the migration pain, it is I think better to skip one version. Hopefully by the time we upgrade to 3.12 or later, we'll have those mechanisms implemented.
